Repository Manohar-mj/codechef_python, pull requests merged in 2022-10, with the labels that each got.

#1 Add README.md
  README.md
Labels: hacktoberfest

#3 Create NUMGAME.cpp
  NUMGAME.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#4 Add StringPermutations.cpp
  Backtracking/StringPermutations.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#6 hashmap1
  Hashmap/contiguous_subarray.py
Labels: hacktoberfest-accepted

#7 Create SUBGCD.cpp
  SUBGCD.cpp
Labels: hacktoberfest-accepted

#8 Courses in an university.py
  Courses in an university.py
Labels: hacktoberfest-accepted

#10 chocolate.cpp
  chocolate.cpp
Labels: hacktoberfest-accepted

#15 Create ChefAndProblemSetting.cpp
  ChefAndProblemSetting.cpp
Labels: hacktoberfest-accepted

#14 Created dayFinder.java
  dayFinder.java
Labels: good first issue
